name: Build test
on: 
  push:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    timeout-minutes: 20
    env:
      IMAGE_NAME: ib-gateway-docker
    steps:
    - uses: actions/checkout@v2
    - name: Setup python
      uses: actions/setup-python@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements-test.txt ]; then pip install -r requirements-test.txt; fi
    - name: Build Docker image
      run: docker build -t $IMAGE_NAME .
    - name: Smoke tests container image
      run: pytest -x
      env:
        TRADE_MODE: ${{ secrets.IB_TRADE_MODE }}
        IB_ACCOUNT: ${{ secrets.IB_ACCOUNT }}
        IB_PASSWORD: ${{ secrets.IB_PASSWORD }}
        IB_PORT: ${{ secrets.IB_PORT }}
        IBGW_PORT: ${{ secrets.IBGW_PORT }}

    - name: Run ib_insync example
      run: |
        docker run --rm \
        -e IB_ACCOUNT=$IB_ACCOUNT \
        -e IB_PASSWORD=$IB_PASSWORD \
        -e TRADE_MODE=paper \
        -e IB_PORT=$IB_PORT \
        -e IBGW_PORT=$IBGW_PORT \
        -e IBGW_WATCHDOG_APP_STARTUP_TIME=60 \
        -e IBGW_WATCHDOG_APP_TIMEOUT=30 \
        -e IBGW_WATCHDOG_CONNECT_TIMEOUT=60 \
        -e IBGW_WATCHDOG_PROBE_TIMEOUT=10 \
        -e IBGW_WATCHDOG_READONLY=True \
        -e IBGW_WATCHDOG_RETRY_DELAY=5 \
        -p $IBGW_PORT:$IBGW_PORT \
        -d \
        $IMAGE_NAME tail -f /dev/null;
        sleep 30;
        pip install ib_insync pandas;
        python examples/ib_insync/scripts/connect_gateway.py;
        docker stop $(docker ps -a -q)
      env:
        TRADE_MODE: ${{ secrets.IB_TRADE_MODE }}
        IB_ACCOUNT: ${{ secrets.IB_ACCOUNT }}
        IB_PASSWORD: ${{ secrets.IB_PASSWORD }}
        IB_PORT: ${{ secrets.IB_PORT }}
        IBGW_PORT: ${{ secrets.IBGW_PORT }}
