name: Deploy to docker hub

on:
   push:
     branches:
        - '*' 
        - '!feature/**' 
        - '!hotfix/**'
        - '!bugfix/**' 
     tags:
       - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@master
      - name: build-push
        uses: docker/build-push-action@v1
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}
            repository: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_IMAGE }}
            tag_with_ref: true
 
